"""empty message

Revision ID: 7d08e9b389fa
Revises:
Create Date: 2019-12-03 21:53:03.648768

"""
from alembic import op
from sqlalchemy_utils.types.uuid import UUIDType
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7d08e9b389fa'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user',
    sa.Column('id', UUIDType(), nullable=False),
    sa.Column('pw_hash', sa.String(length=256), nullable=False),
    sa.Column('pw_expired', sa.DateTime(), nullable=True),
    sa.Column('pw_updated', sa.DateTime(), nullable=True),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('email_updated', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.Column('email_verified', sa.DateTime(timezone=True), nullable=True),
    sa.Column('phone_number', sa.String(length=255), nullable=True),
    sa.Column('phone_number_updated', sa.DateTime(), nullable=True),
    sa.Column('phone_number_verified', sa.Boolean(), nullable=True),
    sa.Column('created', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.Column('updated', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_user_email'), ['email'], unique=True)

    op.create_table('thingy_type',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', UUIDType(), nullable=False),
    sa.Column('tag', sa.String(length=6), nullable=False),
    sa.Column('name', sa.String(length=48), nullable=False),
    sa.Column('description', sa.String(length=256), nullable=True),
    sa.Column('added', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id', 'user_id'),
    sa.UniqueConstraint('user_id', 'tag', name='user_tag_unique')
    )
    with op.batch_alter_table('thingy_type', schema=None) as batch_op:
        batch_op.create_index('thingy_type_user_id_tag_index', ['user_id', 'tag'], unique=False)

    op.create_table('user_profile',
    sa.Column('user_id', UUIDType(), nullable=False),
    sa.Column('given_name', sa.String(length=256), nullable=True),
    sa.Column('family_name', sa.String(length=256), nullable=True),
    sa.Column('middle_name', sa.String(length=256), nullable=True),
    sa.Column('nickname', sa.String(length=256), nullable=True),
    sa.Column('handle', sa.String(length=16), nullable=False),
    sa.Column('visibility', sa.Enum('private', 'public', name='visibility'), nullable=True),
    sa.Column('created', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.Column('updated', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('user_id')
    )
    with op.batch_alter_table('user_profile', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_user_profile_handle'), ['handle'], unique=True)

    op.create_table('thingy',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('type_id', sa.Integer(), nullable=False),
    sa.Column('user_id', UUIDType(), nullable=False),
    sa.Column('added', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['type_id'], ['thingy_type.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id', 'type_id', 'user_id')
    )
    op.create_table('thingy_note',
    sa.Column('user_id', UUIDType(), nullable=False),
    sa.Column('thingy_id', sa.Integer(), nullable=False),
    sa.Column('value', sa.String(length=5000), nullable=False),
    sa.Column('added', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.ForeignKeyConstraint(['thingy_id'], ['thingy.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('user_id', 'thingy_id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('thingy_note')
    op.drop_table('thingy')
    with op.batch_alter_table('user_profile', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_user_profile_handle'))

    op.drop_table('user_profile')
    with op.batch_alter_table('thingy_type', schema=None) as batch_op:
        batch_op.drop_index('thingy_type_user_id_tag_index')

    op.drop_table('thingy_type')
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_user_email'))

    op.drop_table('user')
    # ### end Alembic commands ###
